I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 194, in script
    $ caught_fish = renpy.call_in_new_context("fishing_minigame")
  File "game/script.rpy", line 194, in <module>
    $ caught_fish = renpy.call_in_new_context("fishing_minigame")
ScriptError: could not find label 'fishing_minigame'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 194, in script
    $ caught_fish = renpy.call_in_new_context("fishing_minigame")
  File "C:\Users\1999d\Downloads\renpy-8.0.3-sdk\renpy\ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\1999d\Downloads\renpy-8.0.3-sdk\renpy\python.py", line 1061, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 194, in <module>
    $ caught_fish = renpy.call_in_new_context("fishing_minigame")
  File "C:\Users\1999d\Downloads\renpy-8.0.3-sdk\renpy\game.py", line 346, in call_in_new_context
    return renpy.execution.run_context(False)
  File "C:\Users\1999d\Downloads\renpy-8.0.3-sdk\renpy\execution.py", line 938, in run_context
    context.run()
  File "C:\Users\1999d\Downloads\renpy-8.0.3-sdk\renpy\script.py", line 927, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'fishing_minigame'.

Windows-10-10.0.22631 AMD64
Ren'Py 8.0.3.22090809
Women Want Me Fish Fear Me 1.0
Fri Feb 28 21:11:01 2025
