I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 197, in script
    $ renpy.call_system("python fishing.py", interactive=True)
  File "game/script.rpy", line 197, in <module>
    $ renpy.call_system("python fishing.py", interactive=True)
AttributeError: module 'renpy.exports' has no attribute 'call_system'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 197, in script
    $ renpy.call_system("python fishing.py", interactive=True)
  File "C:\Users\1999d\Downloads\renpy-8.0.3-sdk\renpy\ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\1999d\Downloads\renpy-8.0.3-sdk\renpy\python.py", line 1061, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 197, in <module>
    $ renpy.call_system("python fishing.py", interactive=True)
AttributeError: module 'renpy.exports' has no attribute 'call_system'

Windows-10-10.0.22631 AMD64
Ren'Py 8.0.3.22090809
Women Want Me Fish Fear Me 1.0
Fri Feb 28 14:02:04 2025
